name: daylog
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: 3.0.6
  # flutter_cupertino_date_picker: ^1.0.26+2
  # flutter_cupertino_datetime_picker: ^3.0.0
  package_info_plus: ^1.0.6
  intl: ^0.17.0
  # flutter_material_pickers: ^3.1.4+1
  cupertino_icons: ^1.0.2
  go_router: ^5.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  
  get_it: ^7.2.0
  dio: ^4.0.6
  shared_preferences: ^2.0.16
  logging: ^1.1.0
  flex_color_scheme: ^6.1.2
  google_fonts: ^4.0.3

  another_flushbar: ^1.12.29
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
